package org.bouncycastle.a.i;

import org.bouncycastle.a.p;

/* JADX INFO: loaded from: classes.dex */
public interface d {
    public static final p A;
    public static final p B;
    public static final p C;
    public static final p D;
    public static final p E;
    public static final p F;
    public static final p G;
    public static final p H;
    public static final p I;
    public static final p J;
    public static final p K;
    public static final p L;
    public static final p M;
    public static final p N;
    public static final p O;
    public static final p P;
    public static final p Q;
    public static final p R;
    public static final p S;
    public static final p T;
    public static final p U;
    public static final p V;
    public static final p W;
    public static final p X;
    public static final p Y;
    public static final p Z;
    public static final p a;
    public static final p aa;
    public static final p ab;
    public static final p ac;
    public static final p ad;
    public static final p ae;
    public static final p af;
    public static final p ag;
    public static final p ah;
    public static final p ai;
    public static final p aj;
    public static final p ak;
    public static final p al;
    public static final p am;
    public static final p b;
    public static final p c;
    public static final p d;
    public static final p e;
    public static final p f;
    public static final p g;
    public static final p h;
    public static final p i;
    public static final p j;
    public static final p k;
    public static final p l;
    public static final p m;
    public static final p n;
    public static final p o;
    public static final p p;
    public static final p q;
    public static final p r;
    public static final p s;
    public static final p t;
    public static final p u;
    public static final p v;
    public static final p w;
    public static final p x;
    public static final p y;
    public static final p z;

    static {
        p pVar = new p("1.2.156.10197.1");
        a = pVar;
        b = pVar.b("101.1");
        c = a.b("101.2");
        d = a.b("101.3");
        e = a.b("101.4");
        f = a.b("102.1");
        g = a.b("102.2");
        h = a.b("102.3");
        i = a.b("102.4");
        j = a.b("102.5");
        k = a.b("102.6");
        l = a.b("103.1");
        m = a.b("103.2");
        n = a.b("103.3");
        o = a.b("103.4");
        p = a.b("103.5");
        q = a.b("103.6");
        r = a.b("104.1");
        s = a.b("104.2");
        t = a.b("104.3");
        u = a.b("104.4");
        v = a.b("104.5");
        w = a.b("104.6");
        x = a.b("104.7");
        y = a.b("104.8");
        z = a.b("104.9");
        A = a.b("104.10");
        B = a.b("104.11");
        C = a.b("104.12");
        D = a.b("104.100");
        E = a.b("201");
        F = a.b("301");
        G = a.b("301.1");
        H = a.b("301.2");
        I = a.b("301.3");
        J = a.b("301.101");
        K = I.b("1");
        L = I.b("2");
        M = I.b("2.1");
        N = I.b("2.2");
        O = I.b("2.3");
        P = I.b("2.4");
        Q = I.b("2.5");
        R = I.b("2.6");
        S = I.b("2.7");
        T = I.b("2.8");
        U = I.b("2.9");
        V = I.b("2.10");
        W = I.b("2.11");
        X = a.b("302");
        Y = a.b("302.1");
        Z = a.b("302.2");
        aa = a.b("302.3");
        p pVarB = a.b("401");
        ab = pVarB;
        ac = pVarB.b("2");
        ad = a.b("501");
        ae = a.b("502");
        af = a.b("503");
        ag = a.b("504");
        ah = a.b("505");
        ai = a.b("506");
        aj = a.b("507");
        ak = a.b("520");
        al = a.b("521");
        am = a.b("522");
    }
}
