package org.bouncycastle.e.a;

import org.bouncycastle.a.p;

/* JADX INFO: loaded from: classes.dex */
public interface e {
    public static final p A;
    public static final p B;
    public static final p C;
    public static final p D;
    public static final p E;
    public static final p F;
    public static final p G;
    public static final p H;
    public static final p I;
    public static final p J;
    public static final p K;
    public static final p L;
    public static final p M;
    public static final p N;
    public static final p O;
    public static final p P;
    public static final p Q;
    public static final p R;
    public static final p S;
    public static final p T;
    public static final p U;
    public static final p V;
    public static final p W;
    public static final p X;
    public static final p Y;
    public static final p Z;
    public static final p a;
    public static final p aa;
    public static final p ab;
    public static final p b;
    public static final p c;
    public static final p d;
    public static final p e;
    public static final p f;
    public static final p g;
    public static final p h;
    public static final p i;
    public static final p j;
    public static final p k;
    public static final p l;
    public static final p m;
    public static final p n;
    public static final p o;
    public static final p p;
    public static final p q;
    public static final p r;
    public static final p s;
    public static final p t;
    public static final p u;
    public static final p v;
    public static final p w;
    public static final p x;
    public static final p y;
    public static final p z;

    static {
        p pVar = new p("1.3.6.1.4.1.8301.3.1.3.5.3.2");
        a = pVar;
        b = pVar.b("1");
        c = a.b("2");
        d = a.b("3");
        e = a.b("4");
        f = a.b("5");
        p pVar2 = new p("1.3.6.1.4.1.8301.3.1.3.3");
        g = pVar2;
        h = pVar2.b("1");
        i = g.b("2");
        j = g.b("3");
        k = g.b("4");
        l = g.b("5");
        m = new p("1.3.6.1.4.1.8301.3.1.3.4.1");
        n = new p("1.3.6.1.4.1.8301.3.1.3.4.2");
        o = new p("1.3.6.1.4.1.8301.3.1.3.4.2.1");
        p = new p("1.3.6.1.4.1.8301.3.1.3.4.2.2");
        q = new p("1.3.6.1.4.1.8301.3.1.3.4.2.3");
        r = org.bouncycastle.a.b.a.s;
        s = org.bouncycastle.a.b.a.t;
        t = org.bouncycastle.a.b.a.u;
        u = org.bouncycastle.a.b.a.v;
        v = org.bouncycastle.a.b.a.ad;
        w = org.bouncycastle.a.b.a.w;
        x = org.bouncycastle.a.b.a.x;
        y = org.bouncycastle.a.b.a.y;
        z = org.bouncycastle.a.b.a.z;
        A = org.bouncycastle.a.b.a.A;
        B = org.bouncycastle.a.b.a.B;
        C = org.bouncycastle.a.b.a.C;
        D = org.bouncycastle.a.b.a.D;
        E = org.bouncycastle.a.b.a.E;
        F = org.bouncycastle.a.b.a.F;
        G = org.bouncycastle.a.b.a.G;
        H = org.bouncycastle.a.b.a.H;
        I = org.bouncycastle.a.b.a.I;
        J = org.bouncycastle.a.b.a.J;
        K = org.bouncycastle.a.b.a.K;
        L = org.bouncycastle.a.b.a.L;
        M = org.bouncycastle.a.b.a.M;
        N = org.bouncycastle.a.b.a.N;
        O = x;
        P = y;
        Q = z;
        R = A;
        S = G;
        T = H;
        U = M;
        V = N;
        W = org.bouncycastle.a.b.a.W;
        X = org.bouncycastle.a.b.a.X;
        Y = org.bouncycastle.a.b.a.Y;
        Z = org.bouncycastle.a.b.a.Z;
        aa = org.bouncycastle.a.b.a.aa;
        ab = org.bouncycastle.a.b.a.ab;
    }
}
