package org.bouncycastle.a.aa;

/* JADX INFO: loaded from: classes.dex */
public interface aj {
    public static final org.bouncycastle.a.p A;
    public static final org.bouncycastle.a.p B;
    public static final org.bouncycastle.a.p C;
    public static final org.bouncycastle.a.p D;
    public static final org.bouncycastle.a.p E;
    public static final org.bouncycastle.a.p F;
    public static final org.bouncycastle.a.p G;
    public static final org.bouncycastle.a.p H;
    public static final org.bouncycastle.a.p I;
    public static final org.bouncycastle.a.p J;
    public static final org.bouncycastle.a.p K;
    public static final org.bouncycastle.a.p L;
    public static final org.bouncycastle.a.p M;
    public static final org.bouncycastle.a.p N;
    public static final org.bouncycastle.a.p O;
    public static final org.bouncycastle.a.p P;
    public static final org.bouncycastle.a.p Q;
    public static final org.bouncycastle.a.p R;
    public static final org.bouncycastle.a.p S;
    public static final org.bouncycastle.a.p T;
    public static final org.bouncycastle.a.p U;
    public static final org.bouncycastle.a.p V;
    public static final org.bouncycastle.a.p W;
    public static final org.bouncycastle.a.p X;
    public static final org.bouncycastle.a.p Y;
    public static final org.bouncycastle.a.p Z;
    public static final org.bouncycastle.a.p a;
    public static final org.bouncycastle.a.p aa;
    public static final org.bouncycastle.a.p ab;
    public static final org.bouncycastle.a.p ac;
    public static final org.bouncycastle.a.p ad;
    public static final org.bouncycastle.a.p ae;
    public static final org.bouncycastle.a.p af;
    public static final org.bouncycastle.a.p ag;
    public static final org.bouncycastle.a.p ah;
    public static final org.bouncycastle.a.p ai;
    public static final org.bouncycastle.a.p aj;
    public static final org.bouncycastle.a.p ak;
    public static final org.bouncycastle.a.p al;
    public static final org.bouncycastle.a.p am;
    public static final org.bouncycastle.a.p an;
    public static final org.bouncycastle.a.p ao;
    public static final org.bouncycastle.a.p b;
    public static final org.bouncycastle.a.p c;
    public static final org.bouncycastle.a.p d;
    public static final org.bouncycastle.a.p e;
    public static final org.bouncycastle.a.p f;
    public static final org.bouncycastle.a.p g;
    public static final org.bouncycastle.a.p h;
    public static final org.bouncycastle.a.p i;
    public static final org.bouncycastle.a.p j;
    public static final org.bouncycastle.a.p k;
    public static final org.bouncycastle.a.p l;
    public static final org.bouncycastle.a.p m;
    public static final org.bouncycastle.a.p n;
    public static final org.bouncycastle.a.p o;
    public static final org.bouncycastle.a.p p;
    public static final org.bouncycastle.a.p q;
    public static final org.bouncycastle.a.p r;
    public static final org.bouncycastle.a.p s;
    public static final org.bouncycastle.a.p t;
    public static final org.bouncycastle.a.p u;
    public static final org.bouncycastle.a.p v;
    public static final org.bouncycastle.a.p w;
    public static final org.bouncycastle.a.p x;
    public static final org.bouncycastle.a.p y;
    public static final org.bouncycastle.a.p z;

    static {
        org.bouncycastle.a.p pVar = new org.bouncycastle.a.p("1.2.840.10045");
        a = pVar;
        org.bouncycastle.a.p pVarB = pVar.b("1");
        b = pVarB;
        c = pVarB.b("1");
        org.bouncycastle.a.p pVarB2 = b.b("2");
        d = pVarB2;
        e = pVarB2.b("3.1");
        f = d.b("3.2");
        g = d.b("3.3");
        org.bouncycastle.a.p pVarB3 = a.b("4");
        h = pVarB3;
        i = pVarB3.b("1");
        org.bouncycastle.a.p pVarB4 = a.b("2");
        j = pVarB4;
        k = pVarB4.b("1");
        org.bouncycastle.a.p pVarB5 = h.b("3");
        l = pVarB5;
        m = pVarB5.b("1");
        n = l.b("2");
        o = l.b("3");
        p = l.b("4");
        org.bouncycastle.a.p pVarB6 = a.b("3");
        q = pVarB6;
        org.bouncycastle.a.p pVarB7 = pVarB6.b("0");
        r = pVarB7;
        s = pVarB7.b("1");
        t = r.b("2");
        u = r.b("3");
        v = r.b("4");
        w = r.b("5");
        x = r.b("6");
        y = r.b("7");
        z = r.b("8");
        A = r.b("9");
        B = r.b("10");
        C = r.b("11");
        D = r.b("12");
        E = r.b("13");
        F = r.b("14");
        G = r.b("15");
        H = r.b("16");
        I = r.b("17");
        J = r.b("18");
        K = r.b("19");
        L = r.b("20");
        org.bouncycastle.a.p pVarB8 = q.b("1");
        M = pVarB8;
        N = pVarB8.b("1");
        O = M.b("2");
        P = M.b("3");
        Q = M.b("4");
        R = M.b("5");
        S = M.b("6");
        T = M.b("7");
        U = new org.bouncycastle.a.p("1.2.840.10040.4.1");
        V = new org.bouncycastle.a.p("1.2.840.10040.4.3");
        org.bouncycastle.a.p pVar2 = new org.bouncycastle.a.p("1.3.133.16.840.63.0");
        W = pVar2;
        X = pVar2.b("2");
        Y = W.b("3");
        Z = W.b("16");
        org.bouncycastle.a.p pVar3 = new org.bouncycastle.a.p("1.2.840.10046");
        aa = pVar3;
        ab = pVar3.b("2.1");
        org.bouncycastle.a.p pVarB9 = aa.b("3");
        ac = pVarB9;
        ad = pVarB9.b("1");
        ae = ac.b("2");
        af = ac.b("3");
        ag = ac.b("4");
        ah = ac.b("5");
        ai = ac.b("6");
        aj = ac.b("7");
        ak = ac.b("8");
        org.bouncycastle.a.p pVar4 = new org.bouncycastle.a.p("1.3.133.16.840.9.44");
        al = pVar4;
        org.bouncycastle.a.p pVarB10 = pVar4.b("1");
        am = pVarB10;
        an = pVarB10.b("1");
        ao = am.b("2");
    }
}
