package org.bouncycastle.a.b;

import org.bouncycastle.a.p;

/* JADX INFO: loaded from: classes.dex */
public interface a {
    public static final p A;
    public static final p B;
    public static final p C;
    public static final p D;
    public static final p E;
    public static final p F;
    public static final p G;
    public static final p H;
    public static final p I;
    public static final p J;
    public static final p K;
    public static final p L;
    public static final p M;
    public static final p N;
    public static final p O;
    public static final p P;
    public static final p Q;
    public static final p R;
    public static final p S;
    public static final p T;
    public static final p U;
    public static final p V;
    public static final p W;
    public static final p X;
    public static final p Y;
    public static final p Z;
    public static final p a;
    public static final p aa;
    public static final p ab;
    public static final p ac;
    public static final p ad;
    public static final p b;
    public static final p c;
    public static final p d;
    public static final p e;
    public static final p f;
    public static final p g;
    public static final p h;
    public static final p i;
    public static final p j;
    public static final p k;
    public static final p l;
    public static final p m;
    public static final p n;
    public static final p o;
    public static final p p;
    public static final p q;
    public static final p r;
    public static final p s;
    public static final p t;
    public static final p u;
    public static final p v;
    public static final p w;
    public static final p x;
    public static final p y;
    public static final p z;

    static {
        p pVar = new p("1.3.6.1.4.1.22554");
        a = pVar;
        p pVarB = pVar.b("1");
        b = pVarB;
        c = pVarB.b("1");
        d = b.b("2.1");
        e = b.b("2.2");
        f = b.b("2.3");
        g = b.b("2.4");
        h = c.b("1");
        i = c.b("2");
        j = d.b("1");
        k = d.b("2");
        l = i.b("1.2");
        m = i.b("1.22");
        n = i.b("1.42");
        o = k.b("1.2");
        p = k.b("1.22");
        q = k.b("1.42");
        p pVarB2 = a.b("2");
        r = pVarB2;
        p pVarB3 = pVarB2.b("1");
        s = pVarB3;
        t = pVarB3.b("1");
        u = s.b("2");
        v = s.b("3");
        p pVarB4 = r.b("2");
        w = pVarB4;
        x = pVarB4.b("1");
        y = w.b("2");
        z = w.b("3");
        A = w.b("4");
        B = w.b("5");
        C = w.b("6");
        D = w.b("7");
        E = w.b("8");
        p pVarB5 = r.b("3");
        F = pVarB5;
        G = pVarB5.b("1");
        H = F.b("2");
        I = F.b("3");
        J = F.b("4");
        K = F.b("5");
        L = F.b("6");
        M = F.b("7");
        N = F.b("8");
        O = x;
        P = y;
        Q = z;
        R = A;
        S = G;
        T = H;
        U = M;
        V = N;
        p pVarB6 = r.b("4");
        W = pVarB6;
        X = pVarB6.b("1");
        Y = W.b("2");
        Z = W.b("3");
        aa = W.b("4");
        ab = W.b("5");
        p pVarB7 = a.b("3");
        ac = pVarB7;
        ad = pVarB7.b("1");
    }
}
