package org.bouncycastle.jcajce.provider.symmetric;

import org.bouncycastle.a.b.a;
import org.bouncycastle.a.o.b;
import org.bouncycastle.jcajce.provider.config.ConfigurableProvider;

/* JADX INFO: loaded from: classes.dex */
public class AES$Mappings extends SymmetricAlgorithmProvider {
    private static final String a = AES.class.getName();

    @Override // org.bouncycastle.jcajce.provider.util.AlgorithmProvider
    public final void a(ConfigurableProvider configurableProvider) {
        configurableProvider.a("AlgorithmParameters.AES", a + "$AlgParams");
        configurableProvider.a("Alg.Alias.AlgorithmParameters.2.16.840.1.101.3.4.2", "AES");
        configurableProvider.a("Alg.Alias.AlgorithmParameters.2.16.840.1.101.3.4.22", "AES");
        configurableProvider.a("Alg.Alias.AlgorithmParameters.2.16.840.1.101.3.4.42", "AES");
        configurableProvider.a("Alg.Alias.AlgorithmParameters." + b.u, "AES");
        configurableProvider.a("Alg.Alias.AlgorithmParameters." + b.C, "AES");
        configurableProvider.a("Alg.Alias.AlgorithmParameters." + b.K, "AES");
        configurableProvider.a("AlgorithmParameters.GCM", a + "$AlgParamsGCM");
        configurableProvider.a("Alg.Alias.AlgorithmParameters." + b.y, "GCM");
        configurableProvider.a("Alg.Alias.AlgorithmParameters." + b.G, "GCM");
        configurableProvider.a("Alg.Alias.AlgorithmParameters." + b.O, "GCM");
        configurableProvider.a("AlgorithmParameters.CCM", a + "$AlgParamsCCM");
        configurableProvider.a("Alg.Alias.AlgorithmParameters." + b.z, "CCM");
        configurableProvider.a("Alg.Alias.AlgorithmParameters." + b.H, "CCM");
        configurableProvider.a("Alg.Alias.AlgorithmParameters." + b.P, "CCM");
        configurableProvider.a("AlgorithmParameterGenerator.AES", a + "$AlgParamGen");
        configurableProvider.a("Alg.Alias.AlgorithmParameterGenerator.2.16.840.1.101.3.4.2", "AES");
        configurableProvider.a("Alg.Alias.AlgorithmParameterGenerator.2.16.840.1.101.3.4.22", "AES");
        configurableProvider.a("Alg.Alias.AlgorithmParameterGenerator.2.16.840.1.101.3.4.42", "AES");
        configurableProvider.a("Alg.Alias.AlgorithmParameterGenerator." + b.u, "AES");
        configurableProvider.a("Alg.Alias.AlgorithmParameterGenerator." + b.C, "AES");
        configurableProvider.a("Alg.Alias.AlgorithmParameterGenerator." + b.K, "AES");
        configurableProvider.a("Cipher.AES", AES.a());
        configurableProvider.a("Cipher.AES", a + "$ECB");
        configurableProvider.a("Alg.Alias.Cipher.2.16.840.1.101.3.4.2", "AES");
        configurableProvider.a("Alg.Alias.Cipher.2.16.840.1.101.3.4.22", "AES");
        configurableProvider.a("Alg.Alias.Cipher.2.16.840.1.101.3.4.42", "AES");
        configurableProvider.a("Cipher", b.t, a + "$ECB");
        configurableProvider.a("Cipher", b.B, a + "$ECB");
        configurableProvider.a("Cipher", b.J, a + "$ECB");
        configurableProvider.a("Cipher", b.u, a + "$CBC");
        configurableProvider.a("Cipher", b.C, a + "$CBC");
        configurableProvider.a("Cipher", b.K, a + "$CBC");
        configurableProvider.a("Cipher", b.v, a + "$OFB");
        configurableProvider.a("Cipher", b.D, a + "$OFB");
        configurableProvider.a("Cipher", b.L, a + "$OFB");
        configurableProvider.a("Cipher", b.w, a + "$CFB");
        configurableProvider.a("Cipher", b.E, a + "$CFB");
        configurableProvider.a("Cipher", b.M, a + "$CFB");
        configurableProvider.a("Cipher.AESWRAP", AES.a());
        configurableProvider.a("Cipher.AESWRAP", a + "$Wrap");
        configurableProvider.a("Alg.Alias.Cipher", b.x, "AESWRAP");
        configurableProvider.a("Alg.Alias.Cipher", b.F, "AESWRAP");
        configurableProvider.a("Alg.Alias.Cipher", b.N, "AESWRAP");
        configurableProvider.a("Alg.Alias.Cipher.AESKW", "AESWRAP");
        configurableProvider.a("Cipher.AESWRAPPAD", AES.a());
        configurableProvider.a("Cipher.AESWRAPPAD", a + "$WrapPad");
        configurableProvider.a("Alg.Alias.Cipher", b.A, "AESWRAPPAD");
        configurableProvider.a("Alg.Alias.Cipher", b.I, "AESWRAPPAD");
        configurableProvider.a("Alg.Alias.Cipher", b.Q, "AESWRAPPAD");
        configurableProvider.a("Alg.Alias.Cipher.AESKWP", "AESWRAPPAD");
        configurableProvider.a("Cipher.AESRFC3211WRAP", a + "$RFC3211Wrap");
        configurableProvider.a("Cipher.AESRFC5649WRAP", a + "$RFC5649Wrap");
        configurableProvider.a("AlgorithmParameterGenerator.CCM", a + "$AlgParamGenCCM");
        configurableProvider.a("Alg.Alias.AlgorithmParameterGenerator." + b.z, "CCM");
        configurableProvider.a("Alg.Alias.AlgorithmParameterGenerator." + b.H, "CCM");
        configurableProvider.a("Alg.Alias.AlgorithmParameterGenerator." + b.P, "CCM");
        configurableProvider.a("Cipher.CCM", AES.a());
        configurableProvider.a("Cipher.CCM", a + "$CCM");
        configurableProvider.a("Alg.Alias.Cipher", b.z, "CCM");
        configurableProvider.a("Alg.Alias.Cipher", b.H, "CCM");
        configurableProvider.a("Alg.Alias.Cipher", b.P, "CCM");
        configurableProvider.a("AlgorithmParameterGenerator.GCM", a + "$AlgParamGenGCM");
        configurableProvider.a("Alg.Alias.AlgorithmParameterGenerator." + b.y, "GCM");
        configurableProvider.a("Alg.Alias.AlgorithmParameterGenerator." + b.G, "GCM");
        configurableProvider.a("Alg.Alias.AlgorithmParameterGenerator." + b.O, "GCM");
        configurableProvider.a("Cipher.GCM", AES.a());
        configurableProvider.a("Cipher.GCM", a + "$GCM");
        configurableProvider.a("Alg.Alias.Cipher", b.y, "GCM");
        configurableProvider.a("Alg.Alias.Cipher", b.G, "GCM");
        configurableProvider.a("Alg.Alias.Cipher", b.O, "GCM");
        configurableProvider.a("KeyGenerator.AES", a + "$KeyGen");
        configurableProvider.a("KeyGenerator.2.16.840.1.101.3.4.2", a + "$KeyGen128");
        configurableProvider.a("KeyGenerator.2.16.840.1.101.3.4.22", a + "$KeyGen192");
        configurableProvider.a("KeyGenerator.2.16.840.1.101.3.4.42", a + "$KeyGen256");
        configurableProvider.a("KeyGenerator", b.t, a + "$KeyGen128");
        configurableProvider.a("KeyGenerator", b.u, a + "$KeyGen128");
        configurableProvider.a("KeyGenerator", b.v, a + "$KeyGen128");
        configurableProvider.a("KeyGenerator", b.w, a + "$KeyGen128");
        configurableProvider.a("KeyGenerator", b.B, a + "$KeyGen192");
        configurableProvider.a("KeyGenerator", b.C, a + "$KeyGen192");
        configurableProvider.a("KeyGenerator", b.D, a + "$KeyGen192");
        configurableProvider.a("KeyGenerator", b.E, a + "$KeyGen192");
        configurableProvider.a("KeyGenerator", b.J, a + "$KeyGen256");
        configurableProvider.a("KeyGenerator", b.K, a + "$KeyGen256");
        configurableProvider.a("KeyGenerator", b.L, a + "$KeyGen256");
        configurableProvider.a("KeyGenerator", b.M, a + "$KeyGen256");
        configurableProvider.a("KeyGenerator.AESWRAP", a + "$KeyGen");
        configurableProvider.a("KeyGenerator", b.x, a + "$KeyGen128");
        configurableProvider.a("KeyGenerator", b.F, a + "$KeyGen192");
        configurableProvider.a("KeyGenerator", b.N, a + "$KeyGen256");
        configurableProvider.a("KeyGenerator", b.y, a + "$KeyGen128");
        configurableProvider.a("KeyGenerator", b.G, a + "$KeyGen192");
        configurableProvider.a("KeyGenerator", b.O, a + "$KeyGen256");
        configurableProvider.a("KeyGenerator", b.z, a + "$KeyGen128");
        configurableProvider.a("KeyGenerator", b.H, a + "$KeyGen192");
        configurableProvider.a("KeyGenerator", b.P, a + "$KeyGen256");
        configurableProvider.a("KeyGenerator.AESWRAPPAD", a + "$KeyGen");
        configurableProvider.a("KeyGenerator", b.A, a + "$KeyGen128");
        configurableProvider.a("KeyGenerator", b.I, a + "$KeyGen192");
        configurableProvider.a("KeyGenerator", b.Q, a + "$KeyGen256");
        configurableProvider.a("Mac.AESCMAC", a + "$AESCMAC");
        configurableProvider.a("Mac.AESCCMMAC", a + "$AESCCMMAC");
        configurableProvider.a("Alg.Alias.Mac." + b.z.b(), "AESCCMMAC");
        configurableProvider.a("Alg.Alias.Mac." + b.H.b(), "AESCCMMAC");
        configurableProvider.a("Alg.Alias.Mac." + b.P.b(), "AESCCMMAC");
        configurableProvider.a("Alg.Alias.Cipher", a.l, "PBEWITHSHAAND128BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.Cipher", a.m, "PBEWITHSHAAND192BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.Cipher", a.n, "PBEWITHSHAAND256BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.Cipher", a.o, "PBEWITHSHA256AND128BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.Cipher", a.p, "PBEWITHSHA256AND192BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.Cipher", a.q, "PBEWITHSHA256AND256BITAES-CBC-BC");
        configurableProvider.a("Cipher.PBEWITHSHAAND128BITAES-CBC-BC", a + "$PBEWithSHA1AESCBC128");
        configurableProvider.a("Cipher.PBEWITHSHAAND192BITAES-CBC-BC", a + "$PBEWithSHA1AESCBC192");
        configurableProvider.a("Cipher.PBEWITHSHAAND256BITAES-CBC-BC", a + "$PBEWithSHA1AESCBC256");
        configurableProvider.a("Cipher.PBEWITHSHA256AND128BITAES-CBC-BC", a + "$PBEWithSHA256AESCBC128");
        configurableProvider.a("Cipher.PBEWITHSHA256AND192BITAES-CBC-BC", a + "$PBEWithSHA256AESCBC192");
        configurableProvider.a("Cipher.PBEWITHSHA256AND256BITAES-CBC-BC", a + "$PBEWithSHA256AESCBC256");
        configurableProvider.a("Alg.Alias.Cipher.PBEWITHSHA1AND128BITAES-CBC-BC", "PBEWITHSHAAND128BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.Cipher.PBEWITHSHA1AND192BITAES-CBC-BC", "PBEWITHSHAAND192BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.Cipher.PBEWITHSHA1AND256BITAES-CBC-BC", "PBEWITHSHAAND256BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.Cipher.PBEWITHSHA-1AND128BITAES-CBC-BC", "PBEWITHSHAAND128BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.Cipher.PBEWITHSHA-1AND192BITAES-CBC-BC", "PBEWITHSHAAND192BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.Cipher.PBEWITHSHA-1AND256BITAES-CBC-BC", "PBEWITHSHAAND256BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.Cipher.PBEWITHSHAAND128BITAES-BC", "PBEWITHSHAAND128BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.Cipher.PBEWITHSHAAND192BITAES-BC", "PBEWITHSHAAND192BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.Cipher.PBEWITHSHAAND256BITAES-BC", "PBEWITHSHAAND256BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.Cipher.PBEWITHSHA1AND128BITAES-BC", "PBEWITHSHAAND128BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.Cipher.PBEWITHSHA1AND192BITAES-BC", "PBEWITHSHAAND192BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.Cipher.PBEWITHSHA1AND256BITAES-BC", "PBEWITHSHAAND256BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.Cipher.PBEWITHSHA-1AND128BITAES-BC", "PBEWITHSHAAND128BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.Cipher.PBEWITHSHA-1AND192BITAES-BC", "PBEWITHSHAAND192BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.Cipher.PBEWITHSHA-1AND256BITAES-BC", "PBEWITHSHAAND256BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.Cipher.PBEWITHSHA-256AND128BITAES-CBC-BC", "PBEWITHSHA256AND128BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.Cipher.PBEWITHSHA-256AND192BITAES-CBC-BC", "PBEWITHSHA256AND192BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.Cipher.PBEWITHSHA-256AND256BITAES-CBC-BC", "PBEWITHSHA256AND256BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.Cipher.PBEWITHSHA256AND128BITAES-BC", "PBEWITHSHA256AND128BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.Cipher.PBEWITHSHA256AND192BITAES-BC", "PBEWITHSHA256AND192BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.Cipher.PBEWITHSHA256AND256BITAES-BC", "PBEWITHSHA256AND256BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.Cipher.PBEWITHSHA-256AND128BITAES-BC", "PBEWITHSHA256AND128BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.Cipher.PBEWITHSHA-256AND192BITAES-BC", "PBEWITHSHA256AND192BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.Cipher.PBEWITHSHA-256AND256BITAES-BC", "PBEWITHSHA256AND256BITAES-CBC-BC");
        configurableProvider.a("Cipher.PBEWITHMD5AND128BITAES-CBC-OPENSSL", a + "$PBEWithAESCBC");
        configurableProvider.a("Cipher.PBEWITHMD5AND192BITAES-CBC-OPENSSL", a + "$PBEWithAESCBC");
        configurableProvider.a("Cipher.PBEWITHMD5AND256BITAES-CBC-OPENSSL", a + "$PBEWithAESCBC");
        configurableProvider.a("SecretKeyFactory.AES", a + "$KeyFactory");
        configurableProvider.a("SecretKeyFactory", b.s, a + "$KeyFactory");
        configurableProvider.a("SecretKeyFactory.PBEWITHMD5AND128BITAES-CBC-OPENSSL", a + "$PBEWithMD5And128BitAESCBCOpenSSL");
        configurableProvider.a("SecretKeyFactory.PBEWITHMD5AND192BITAES-CBC-OPENSSL", a + "$PBEWithMD5And192BitAESCBCOpenSSL");
        configurableProvider.a("SecretKeyFactory.PBEWITHMD5AND256BITAES-CBC-OPENSSL", a + "$PBEWithMD5And256BitAESCBCOpenSSL");
        configurableProvider.a("SecretKeyFactory.PBEWITHSHAAND128BITAES-CBC-BC", a + "$PBEWithSHAAnd128BitAESBC");
        configurableProvider.a("SecretKeyFactory.PBEWITHSHAAND192BITAES-CBC-BC", a + "$PBEWithSHAAnd192BitAESBC");
        configurableProvider.a("SecretKeyFactory.PBEWITHSHAAND256BITAES-CBC-BC", a + "$PBEWithSHAAnd256BitAESBC");
        configurableProvider.a("SecretKeyFactory.PBEWITHSHA256AND128BITAES-CBC-BC", a + "$PBEWithSHA256And128BitAESBC");
        configurableProvider.a("SecretKeyFactory.PBEWITHSHA256AND192BITAES-CBC-BC", a + "$PBEWithSHA256And192BitAESBC");
        configurableProvider.a("SecretKeyFactory.PBEWITHSHA256AND256BITAES-CBC-BC", a + "$PBEWithSHA256And256BitAESBC");
        configurableProvider.a("Alg.Alias.SecretKeyFactory.PBEWITHSHA1AND128BITAES-CBC-BC", "PBEWITHSHAAND128BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.SecretKeyFactory.PBEWITHSHA1AND192BITAES-CBC-BC", "PBEWITHSHAAND192BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.SecretKeyFactory.PBEWITHSHA1AND256BITAES-CBC-BC", "PBEWITHSHAAND256BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.SecretKeyFactory.PBEWITHSHA-1AND128BITAES-CBC-BC", "PBEWITHSHAAND128BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.SecretKeyFactory.PBEWITHSHA-1AND192BITAES-CBC-BC", "PBEWITHSHAAND192BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.SecretKeyFactory.PBEWITHSHA-1AND256BITAES-CBC-BC", "PBEWITHSHAAND256BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.SecretKeyFactory.PBEWITHSHA-256AND128BITAES-CBC-BC", "PBEWITHSHA256AND128BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.SecretKeyFactory.PBEWITHSHA-256AND192BITAES-CBC-BC", "PBEWITHSHA256AND192BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.SecretKeyFactory.PBEWITHSHA-256AND256BITAES-CBC-BC", "PBEWITHSHA256AND256BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.SecretKeyFactory.PBEWITHSHA-256AND128BITAES-BC", "PBEWITHSHA256AND128BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.SecretKeyFactory.PBEWITHSHA-256AND192BITAES-BC", "PBEWITHSHA256AND192BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.SecretKeyFactory.PBEWITHSHA-256AND256BITAES-BC", "PBEWITHSHA256AND256BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.SecretKeyFactory", a.l, "PBEWITHSHAAND128BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.SecretKeyFactory", a.m, "PBEWITHSHAAND192BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.SecretKeyFactory", a.n, "PBEWITHSHAAND256BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.SecretKeyFactory", a.o, "PBEWITHSHA256AND128BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.SecretKeyFactory", a.p, "PBEWITHSHA256AND192BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.SecretKeyFactory", a.q, "PBEWITHSHA256AND256BITAES-CBC-BC");
        configurableProvider.a("Alg.Alias.AlgorithmParameters.PBEWITHSHAAND128BITAES-CBC-BC", "PKCS12PBE");
        configurableProvider.a("Alg.Alias.AlgorithmParameters.PBEWITHSHAAND192BITAES-CBC-BC", "PKCS12PBE");
        configurableProvider.a("Alg.Alias.AlgorithmParameters.PBEWITHSHAAND256BITAES-CBC-BC", "PKCS12PBE");
        configurableProvider.a("Alg.Alias.AlgorithmParameters.PBEWITHSHA256AND128BITAES-CBC-BC", "PKCS12PBE");
        configurableProvider.a("Alg.Alias.AlgorithmParameters.PBEWITHSHA256AND192BITAES-CBC-BC", "PKCS12PBE");
        configurableProvider.a("Alg.Alias.AlgorithmParameters.PBEWITHSHA256AND256BITAES-CBC-BC", "PKCS12PBE");
        configurableProvider.a("Alg.Alias.AlgorithmParameters.PBEWITHSHA1AND128BITAES-CBC-BC", "PKCS12PBE");
        configurableProvider.a("Alg.Alias.AlgorithmParameters.PBEWITHSHA1AND192BITAES-CBC-BC", "PKCS12PBE");
        configurableProvider.a("Alg.Alias.AlgorithmParameters.PBEWITHSHA1AND256BITAES-CBC-BC", "PKCS12PBE");
        configurableProvider.a("Alg.Alias.AlgorithmParameters.PBEWITHSHA-1AND128BITAES-CBC-BC", "PKCS12PBE");
        configurableProvider.a("Alg.Alias.AlgorithmParameters.PBEWITHSHA-1AND192BITAES-CBC-BC", "PKCS12PBE");
        configurableProvider.a("Alg.Alias.AlgorithmParameters.PBEWITHSHA-1AND256BITAES-CBC-BC", "PKCS12PBE");
        configurableProvider.a("Alg.Alias.AlgorithmParameters.PBEWITHSHA-256AND128BITAES-CBC-BC", "PKCS12PBE");
        configurableProvider.a("Alg.Alias.AlgorithmParameters.PBEWITHSHA-256AND192BITAES-CBC-BC", "PKCS12PBE");
        configurableProvider.a("Alg.Alias.AlgorithmParameters.PBEWITHSHA-256AND256BITAES-CBC-BC", "PKCS12PBE");
        configurableProvider.a("Alg.Alias.AlgorithmParameters." + a.l.b(), "PKCS12PBE");
        configurableProvider.a("Alg.Alias.AlgorithmParameters." + a.m.b(), "PKCS12PBE");
        configurableProvider.a("Alg.Alias.AlgorithmParameters." + a.n.b(), "PKCS12PBE");
        configurableProvider.a("Alg.Alias.AlgorithmParameters." + a.o.b(), "PKCS12PBE");
        configurableProvider.a("Alg.Alias.AlgorithmParameters." + a.p.b(), "PKCS12PBE");
        configurableProvider.a("Alg.Alias.AlgorithmParameters." + a.q.b(), "PKCS12PBE");
        b(configurableProvider, "AES", a + "$AESGMAC", a + "$KeyGen128");
        c(configurableProvider, "AES", a + "$Poly1305", a + "$Poly1305KeyGen");
    }
}
