package org.bouncycastle.a.o;

import org.bouncycastle.a.p;

/* JADX INFO: loaded from: classes.dex */
public interface b {
    public static final p A;
    public static final p B;
    public static final p C;
    public static final p D;
    public static final p E;
    public static final p F;
    public static final p G;
    public static final p H;
    public static final p I;
    public static final p J;
    public static final p K;
    public static final p L;
    public static final p M;
    public static final p N;
    public static final p O;
    public static final p P;
    public static final p Q;
    public static final p R;
    public static final p S;
    public static final p T;
    public static final p U;
    public static final p V;
    public static final p W;
    public static final p X;
    public static final p Y;
    public static final p Z;
    public static final p a;
    public static final p aa;
    public static final p ab;
    public static final p ac;
    public static final p ad;
    public static final p ae;
    public static final p af;
    public static final p ag;
    public static final p ah;
    public static final p ai;
    public static final p b;
    public static final p c;
    public static final p d;
    public static final p e;
    public static final p f;
    public static final p g;
    public static final p h;
    public static final p i;
    public static final p j;
    public static final p k;
    public static final p l;
    public static final p m;
    public static final p n;
    public static final p o;
    public static final p p;
    public static final p q;
    public static final p r;
    public static final p s;
    public static final p t;
    public static final p u;
    public static final p v;
    public static final p w;
    public static final p x;
    public static final p y;
    public static final p z;

    static {
        p pVar = new p("2.16.840.1.101.3.4");
        a = pVar;
        p pVarB = pVar.b("2");
        b = pVarB;
        c = pVarB.b("1");
        d = b.b("2");
        e = b.b("3");
        f = b.b("4");
        g = b.b("5");
        h = b.b("6");
        i = b.b("7");
        j = b.b("8");
        k = b.b("9");
        l = b.b("10");
        m = b.b("11");
        n = b.b("12");
        o = b.b("13");
        p = b.b("14");
        q = b.b("15");
        r = b.b("16");
        p pVarB2 = a.b("1");
        s = pVarB2;
        t = pVarB2.b("1");
        u = s.b("2");
        v = s.b("3");
        w = s.b("4");
        x = s.b("5");
        y = s.b("6");
        z = s.b("7");
        A = s.b("8");
        B = s.b("21");
        C = s.b("22");
        D = s.b("23");
        E = s.b("24");
        F = s.b("25");
        G = s.b("26");
        H = s.b("27");
        I = s.b("28");
        J = s.b("41");
        K = s.b("42");
        L = s.b("43");
        M = s.b("44");
        N = s.b("45");
        O = s.b("46");
        P = s.b("47");
        Q = s.b("48");
        p pVarB3 = a.b("3");
        R = pVarB3;
        S = pVarB3;
        T = R.b("1");
        U = R.b("2");
        V = R.b("3");
        W = R.b("4");
        X = R.b("5");
        Y = R.b("6");
        Z = R.b("7");
        aa = R.b("8");
        ab = R.b("9");
        ac = R.b("10");
        ad = R.b("11");
        ae = R.b("12");
        af = R.b("13");
        ag = R.b("14");
        ah = R.b("15");
        ai = R.b("16");
    }
}
