package org.bouncycastle.a.u;

/* JADX INFO: loaded from: classes.dex */
public interface aj {
    public static final org.bouncycastle.a.p A;
    public static final org.bouncycastle.a.p B;
    public static final org.bouncycastle.a.p C;
    public static final org.bouncycastle.a.p D;
    public static final org.bouncycastle.a.p E;
    public static final org.bouncycastle.a.p F;
    public static final org.bouncycastle.a.p G;
    public static final org.bouncycastle.a.p H;
    public static final org.bouncycastle.a.p I;
    public static final org.bouncycastle.a.p J;
    public static final org.bouncycastle.a.p K;
    public static final org.bouncycastle.a.p L;
    public static final org.bouncycastle.a.p M;
    public static final org.bouncycastle.a.p N;
    public static final org.bouncycastle.a.p O;
    public static final org.bouncycastle.a.p P;
    public static final org.bouncycastle.a.p Q;
    public static final org.bouncycastle.a.p R;
    public static final org.bouncycastle.a.p S;
    public static final org.bouncycastle.a.p T;
    public static final org.bouncycastle.a.p U;
    public static final org.bouncycastle.a.p V;
    public static final org.bouncycastle.a.p W;
    public static final org.bouncycastle.a.p X;
    public static final org.bouncycastle.a.p Y;
    public static final org.bouncycastle.a.p a;
    public static final org.bouncycastle.a.p b;
    public static final org.bouncycastle.a.p c;
    public static final org.bouncycastle.a.p d;
    public static final org.bouncycastle.a.p e;
    public static final org.bouncycastle.a.p f;
    public static final org.bouncycastle.a.p g;
    public static final org.bouncycastle.a.p h;
    public static final org.bouncycastle.a.p i;
    public static final org.bouncycastle.a.p j;
    public static final org.bouncycastle.a.p k;
    public static final org.bouncycastle.a.p l;
    public static final org.bouncycastle.a.p m;
    public static final org.bouncycastle.a.p n;
    public static final org.bouncycastle.a.p o;
    public static final org.bouncycastle.a.p p;
    public static final org.bouncycastle.a.p q;
    public static final org.bouncycastle.a.p r;
    public static final org.bouncycastle.a.p s;
    public static final org.bouncycastle.a.p t;
    public static final org.bouncycastle.a.p u;
    public static final org.bouncycastle.a.p v;
    public static final org.bouncycastle.a.p w;
    public static final org.bouncycastle.a.p x;
    public static final org.bouncycastle.a.p y;
    public static final org.bouncycastle.a.p z;

    static {
        org.bouncycastle.a.p pVar = new org.bouncycastle.a.p("1.3.132.0");
        a = pVar;
        b = pVar.b("1");
        c = a.b("2");
        d = a.b("3");
        e = a.b("4");
        f = a.b("5");
        g = a.b("6");
        h = a.b("7");
        i = a.b("8");
        j = a.b("9");
        k = a.b("10");
        l = a.b("15");
        m = a.b("16");
        n = a.b("17");
        o = a.b("22");
        p = a.b("23");
        q = a.b("24");
        r = a.b("25");
        s = a.b("26");
        t = a.b("27");
        u = a.b("28");
        v = a.b("29");
        w = a.b("30");
        x = a.b("31");
        y = a.b("32");
        z = a.b("33");
        A = a.b("34");
        B = a.b("35");
        C = a.b("36");
        D = a.b("37");
        E = a.b("38");
        F = a.b("39");
        G = org.bouncycastle.a.aa.aj.N;
        H = org.bouncycastle.a.aa.aj.T;
        org.bouncycastle.a.p pVar2 = new org.bouncycastle.a.p("1.3.132.1");
        I = pVar2;
        J = pVar2.b("11.0");
        K = I.b("11.1");
        L = I.b("11.2");
        M = I.b("11.3");
        N = I.b("14.0");
        O = I.b("14.1");
        P = I.b("14.2");
        Q = I.b("14.3");
        R = I.b("15.0");
        S = I.b("15.1");
        T = I.b("15.2");
        U = I.b("15.3");
        V = I.b("16.0");
        W = I.b("16.1");
        X = I.b("16.2");
        Y = I.b("16.3");
    }
}
