package org.bouncycastle.a.s;

/* JADX INFO: loaded from: classes.dex */
public interface n {
    public static final org.bouncycastle.a.p A;
    public static final org.bouncycastle.a.p B;
    public static final org.bouncycastle.a.p C;
    public static final org.bouncycastle.a.p D;
    public static final org.bouncycastle.a.p E;
    public static final org.bouncycastle.a.p F;
    public static final org.bouncycastle.a.p G;
    public static final org.bouncycastle.a.p H;
    public static final org.bouncycastle.a.p I;
    public static final org.bouncycastle.a.p J;
    public static final org.bouncycastle.a.p K;
    public static final org.bouncycastle.a.p L;
    public static final org.bouncycastle.a.p M;
    public static final org.bouncycastle.a.p N;
    public static final org.bouncycastle.a.p O;
    public static final org.bouncycastle.a.p P;
    public static final org.bouncycastle.a.p Q;
    public static final org.bouncycastle.a.p R;
    public static final org.bouncycastle.a.p S;
    public static final org.bouncycastle.a.p T;
    public static final org.bouncycastle.a.p U;
    public static final org.bouncycastle.a.p V;
    public static final org.bouncycastle.a.p W;
    public static final org.bouncycastle.a.p X;
    public static final org.bouncycastle.a.p Y;
    public static final org.bouncycastle.a.p Z;
    public static final org.bouncycastle.a.p aA;
    public static final org.bouncycastle.a.p aB;
    public static final org.bouncycastle.a.p aC;
    public static final org.bouncycastle.a.p aD;
    public static final org.bouncycastle.a.p aE;
    public static final org.bouncycastle.a.p aF;
    public static final org.bouncycastle.a.p aG;
    public static final org.bouncycastle.a.p aH;
    public static final org.bouncycastle.a.p aI;
    public static final org.bouncycastle.a.p aJ;
    public static final org.bouncycastle.a.p aK;
    public static final org.bouncycastle.a.p aL;
    public static final org.bouncycastle.a.p aM;
    public static final org.bouncycastle.a.p aN;
    public static final org.bouncycastle.a.p aO;
    public static final org.bouncycastle.a.p aP;
    public static final org.bouncycastle.a.p aQ;
    public static final org.bouncycastle.a.p aR;
    public static final org.bouncycastle.a.p aS;
    public static final org.bouncycastle.a.p aT;
    public static final org.bouncycastle.a.p aU;
    public static final org.bouncycastle.a.p aV;
    public static final org.bouncycastle.a.p aW;
    public static final org.bouncycastle.a.p aX;
    public static final org.bouncycastle.a.p aY;
    public static final org.bouncycastle.a.p aZ;
    public static final org.bouncycastle.a.p aa;
    public static final org.bouncycastle.a.p ab;
    public static final org.bouncycastle.a.p ac;
    public static final org.bouncycastle.a.p ad;
    public static final org.bouncycastle.a.p ae;
    public static final org.bouncycastle.a.p af;
    public static final org.bouncycastle.a.p ag;
    public static final org.bouncycastle.a.p ah;
    public static final org.bouncycastle.a.p ai;
    public static final org.bouncycastle.a.p aj;
    public static final org.bouncycastle.a.p ak;
    public static final org.bouncycastle.a.p al;
    public static final org.bouncycastle.a.p am;
    public static final org.bouncycastle.a.p an;
    public static final org.bouncycastle.a.p ao;
    public static final org.bouncycastle.a.p ap;
    public static final org.bouncycastle.a.p aq;
    public static final org.bouncycastle.a.p ar;
    public static final org.bouncycastle.a.p as;
    public static final org.bouncycastle.a.p at;
    public static final org.bouncycastle.a.p au;
    public static final org.bouncycastle.a.p av;
    public static final org.bouncycastle.a.p aw;
    public static final org.bouncycastle.a.p ax;
    public static final org.bouncycastle.a.p ay;
    public static final org.bouncycastle.a.p az;
    public static final org.bouncycastle.a.p bA;
    public static final org.bouncycastle.a.p bB;
    public static final org.bouncycastle.a.p bC;
    public static final org.bouncycastle.a.p bD;
    public static final org.bouncycastle.a.p bE;
    public static final org.bouncycastle.a.p bF;
    public static final org.bouncycastle.a.p bG;
    public static final org.bouncycastle.a.p bH;
    public static final org.bouncycastle.a.p bI;
    public static final org.bouncycastle.a.p bJ;
    public static final org.bouncycastle.a.p bK;
    public static final org.bouncycastle.a.p bL;
    public static final org.bouncycastle.a.p bM;
    public static final org.bouncycastle.a.p bN;
    public static final org.bouncycastle.a.p ba;
    public static final org.bouncycastle.a.p bb;
    public static final org.bouncycastle.a.p bc;
    public static final org.bouncycastle.a.p bd;
    public static final org.bouncycastle.a.p be;
    public static final org.bouncycastle.a.p bf;
    public static final org.bouncycastle.a.p bg;
    public static final org.bouncycastle.a.p bh;
    public static final org.bouncycastle.a.p bi;
    public static final org.bouncycastle.a.p bj;
    public static final org.bouncycastle.a.p bk;
    public static final org.bouncycastle.a.p bl;
    public static final org.bouncycastle.a.p bm;
    public static final org.bouncycastle.a.p bn;
    public static final org.bouncycastle.a.p bo;
    public static final org.bouncycastle.a.p bp;
    public static final org.bouncycastle.a.p bq;
    public static final org.bouncycastle.a.p br;
    public static final org.bouncycastle.a.p bs;
    public static final org.bouncycastle.a.p bt;
    public static final org.bouncycastle.a.p bu;
    public static final org.bouncycastle.a.p bv;
    public static final org.bouncycastle.a.p bw;
    public static final org.bouncycastle.a.p bx;
    public static final org.bouncycastle.a.p by;
    public static final org.bouncycastle.a.p bz;
    public static final org.bouncycastle.a.p d;
    public static final org.bouncycastle.a.p e;
    public static final org.bouncycastle.a.p e_;
    public static final org.bouncycastle.a.p f_;
    public static final org.bouncycastle.a.p g_;
    public static final org.bouncycastle.a.p h;
    public static final org.bouncycastle.a.p h_;
    public static final org.bouncycastle.a.p i_;
    public static final org.bouncycastle.a.p j_;
    public static final org.bouncycastle.a.p k;
    public static final org.bouncycastle.a.p k_;
    public static final org.bouncycastle.a.p l_;
    public static final org.bouncycastle.a.p m_;
    public static final org.bouncycastle.a.p n_;
    public static final org.bouncycastle.a.p o_;
    public static final org.bouncycastle.a.p p_;
    public static final org.bouncycastle.a.p q_;
    public static final org.bouncycastle.a.p r_;
    public static final org.bouncycastle.a.p s;
    public static final org.bouncycastle.a.p s_;
    public static final org.bouncycastle.a.p t_;
    public static final org.bouncycastle.a.p v;
    public static final org.bouncycastle.a.p w;
    public static final org.bouncycastle.a.p x;
    public static final org.bouncycastle.a.p y;
    public static final org.bouncycastle.a.p z;

    static {
        org.bouncycastle.a.p pVar = new org.bouncycastle.a.p("1.2.840.113549.1.1");
        e_ = pVar;
        f_ = pVar.b("1");
        g_ = e_.b("2");
        d = e_.b("3");
        e = e_.b("4");
        h_ = e_.b("5");
        i_ = e_.b("6");
        h = e_.b("7");
        j_ = e_.b("8");
        k_ = e_.b("9");
        k = e_.b("10");
        l_ = e_.b("11");
        m_ = e_.b("12");
        n_ = e_.b("13");
        o_ = e_.b("14");
        p_ = e_.b("15");
        q_ = e_.b("16");
        org.bouncycastle.a.p pVar2 = new org.bouncycastle.a.p("1.2.840.113549.1.3");
        r_ = pVar2;
        s = pVar2.b("1");
        org.bouncycastle.a.p pVar3 = new org.bouncycastle.a.p("1.2.840.113549.1.5");
        s_ = pVar3;
        t_ = pVar3.b("1");
        v = s_.b("4");
        w = s_.b("3");
        x = s_.b("6");
        y = s_.b("10");
        z = s_.b("11");
        A = s_.b("13");
        B = s_.b("12");
        org.bouncycastle.a.p pVar4 = new org.bouncycastle.a.p("1.2.840.113549.3");
        C = pVar4;
        D = pVar4.b("7");
        E = C.b("2");
        F = C.b("4");
        org.bouncycastle.a.p pVar5 = new org.bouncycastle.a.p("1.2.840.113549.2");
        G = pVar5;
        H = pVar5.b("2");
        I = G.b("4");
        J = G.b("5");
        K = G.b("7").c();
        L = G.b("8").c();
        M = G.b("9").c();
        N = G.b("10").c();
        O = G.b("11").c();
        P = new org.bouncycastle.a.p("1.2.840.113549.1.7").c();
        Q = new org.bouncycastle.a.p("1.2.840.113549.1.7.1").c();
        R = new org.bouncycastle.a.p("1.2.840.113549.1.7.2").c();
        S = new org.bouncycastle.a.p("1.2.840.113549.1.7.3").c();
        T = new org.bouncycastle.a.p("1.2.840.113549.1.7.4").c();
        U = new org.bouncycastle.a.p("1.2.840.113549.1.7.5").c();
        V = new org.bouncycastle.a.p("1.2.840.113549.1.7.6").c();
        org.bouncycastle.a.p pVar6 = new org.bouncycastle.a.p("1.2.840.113549.1.9");
        W = pVar6;
        X = pVar6.b("1").c();
        Y = W.b("2").c();
        Z = W.b("3").c();
        aa = W.b("4").c();
        ab = W.b("5").c();
        ac = W.b("6").c();
        ad = W.b("7").c();
        ae = W.b("8").c();
        af = W.b("9").c();
        ag = W.b("13").c();
        ah = W.b("14").c();
        ai = W.b("15").c();
        aj = W.b("16").c();
        ak = W.b("20").c();
        al = W.b("21").c();
        am = W.b("22.1");
        org.bouncycastle.a.p pVarB = W.b("22");
        an = pVarB;
        ao = pVarB.b("1").c();
        ap = an.b("2").c();
        org.bouncycastle.a.p pVarB2 = W.b("23");
        aq = pVarB2;
        ar = pVarB2.b("1").c();
        as = W.b("52").c();
        at = W.b("15.1");
        au = W.b("15.2");
        av = W.b("15.3");
        org.bouncycastle.a.p pVar7 = new org.bouncycastle.a.p("1.2.840.113549.1.9.16.1");
        aw = pVar7;
        ax = pVar7.b("2");
        ay = aw.b("4");
        az = aw.b("9");
        aA = aw.b("23");
        aB = aw.b("31");
        org.bouncycastle.a.p pVarB3 = aj.b("3");
        aC = pVarB3;
        aD = pVarB3.b("9");
        aE = aC.b("14");
        org.bouncycastle.a.p pVar8 = new org.bouncycastle.a.p("1.2.840.113549.1.9.16.6");
        aF = pVar8;
        aG = pVar8.b("1");
        aH = aF.b("2");
        aI = aF.b("3");
        aJ = aF.b("4");
        aK = aF.b("5");
        aL = aF.b("6");
        org.bouncycastle.a.p pVar9 = new org.bouncycastle.a.p("1.2.840.113549.1.9.16.2");
        aM = pVar9;
        aN = pVar9.b("1");
        aO = aM.b("4");
        aP = aM.b("5");
        aQ = aM.b("10");
        aR = aM.b("11");
        aS = aM.b("12");
        aT = aM.b("47");
        aU = aM.b("7");
        aV = aM.b("14");
        aW = aM.b("15");
        aX = aM.b("16");
        aY = aM.b("17");
        aZ = aM.b("18");
        ba = aM.b("19");
        bb = aM.b("20");
        bc = aM.b("21");
        bd = aM.b("22");
        be = aM.b("23");
        bf = aM.b("24");
        bg = aM.b("25");
        bh = aM.b("26");
        bi = aM.b("27");
        bj = aM.b("37");
        bk = aM.b("38");
        bl = aM.b("54");
        bm = aM.b("43");
        bn = aM.b("40");
        bo = aW;
        bp = aX;
        bq = aY;
        br = ba;
        bs = new org.bouncycastle.a.p("1.2.840.113549.1.9.16.5.1");
        bt = new org.bouncycastle.a.p("1.2.840.113549.1.9.16.5.2");
        org.bouncycastle.a.p pVar10 = new org.bouncycastle.a.p("1.2.840.113549.1.12");
        bu = pVar10;
        org.bouncycastle.a.p pVarB4 = pVar10.b("10.1");
        bv = pVarB4;
        bw = pVarB4.b("1");
        bx = bv.b("2");
        by = bv.b("3");
        bz = bv.b("4");
        bA = bv.b("5");
        bB = bv.b("6");
        org.bouncycastle.a.p pVarB5 = bu.b("1");
        bC = pVarB5;
        bD = pVarB5.b("1");
        bE = bC.b("2");
        bF = bC.b("3");
        bG = bC.b("4");
        bH = bC.b("5");
        bI = bC.b("6");
        bJ = bC.b("6");
        bK = new org.bouncycastle.a.p("1.2.840.113549.1.9.16.3.6");
        bL = new org.bouncycastle.a.p("1.2.840.113549.1.9.16.3.7");
        bM = new org.bouncycastle.a.p("1.2.840.113549.1.9.16.3.5");
        bN = new org.bouncycastle.a.p("1.2.840.113549.1.9.16.3.10");
    }
}
